version: "3.7"

services: 
  web:
    build: .
    restart: unless-stopped
    image: frontend
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - db-ss:/code
    ports:
      - "8000:8000"

    depends_on:
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  # migration:
  #   image: frontend
  #   command: sh -c "echo yes | python manage.py collectstatic"
  #     - db-ss:/code
  #   depends_on:
  #     - db

volumes:
  db-ss:


#python manage.py makemigrations core && python manage.py migrate && 